### ISSUE TITLE
Implement MVP (Core)

### ISSUE THREAD

**Issue by csalmhof** [CheetUnit/CheetUnit#1]
- [x] Create maven project for CheetUnit
- [x] Implement a core
- [x] Implement REST-Endpoint, that can be deployed within a test application on wildlfy or jboss. REST Endpoint must be delivered as a jar, that can be packed in a war archive.
- [x] Implement a tiny war appliaction with a single domain service that will be started on wildfly.
- [x] Implement first test, that logs "Hello World" on server.

DoD
- [x] 4 artefacts: cheetunit-wildfly, cheetunit-core, cheetunit-test, example

Assigments:
- Patrik: cheetunit-test
- Egor: cheetunit-api, cheetunit-core
- Christian: Test-Examples (eine WAR applikation auf JBoss mit 3-4 domain Services)
