### ISSUE TITLE
Write Documentation (Getting Started)

### ISSUE THREAD

**Issue by csalmhof** [CheetUnit/CheetUnit#2]
- [x] Wiki for internals
- [x] Meaningful READ.ME
- [x] Javadoc for APIs
- [x] Git pages for product desciption and getting started
--------------

Good practice example is assertj
* https://github.com/assertj/assertj-core 
* https://assertj.github.io/doc
--> https://cheetunit.github.io/doc/

**README**
- [x] Badges (CI status, maven central version etc)
- [x] Introduction Section with short description and navigation bullet points to different other sections + Link to Git-Hub-Pages as bullet point; If you want to contribute use tag 
- [x] CheetUnit's goals 
- [x] Quick start (references to GitHub-Pages URL) 
- [x] Latest News
- [x] Contribution

**Github-Pages**
- [x] CheetUnit Overview (short description of different modules)
- [x] Quick Start 
- [x] CheetUnit Wildfly 
- [x] CheetUnit Test
- [x] CheetUnit Examples 
- [x] Release Notes (for the whole project, not for every module)
- [x] support versions (Java, JavaEE, JUnit, Application Servers)

**Comment by patholzer** [comment]
![alf](https://user-images.githubusercontent.com/47662203/109296682-08205780-7831-11eb-8408-53b1bd4b2c13.gif)
